# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea2ced0a77facdc2f68c1fe4f95339934d5ef4953918f309d414f68fbd582bf70a8cfaa173196c231507c6e313f07a98586276a947a7379bcd9a9be069599963

test:
  secret_key_base: ae1cb1c145c045c604a24b94aea6f88f16605fc5dcb4dcc052378f79ee53436b32221ed61af0ec60e7af45c35ff511d847846b6c8d1bd4816dd7317dfdd64a56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
